package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReviewReminderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewReminderAllPropertiesEquals(ReviewReminder expected, ReviewReminder actual) {
        assertReviewReminderAutoGeneratedPropertiesEquals(expected, actual);
        assertReviewReminderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewReminderAllUpdatablePropertiesEquals(ReviewReminder expected, ReviewReminder actual) {
        assertReviewReminderUpdatableFieldsEquals(expected, actual);
        assertReviewReminderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewReminderAutoGeneratedPropertiesEquals(ReviewReminder expected, ReviewReminder actual) {
        assertThat(actual)
            .as("Verify ReviewReminder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewReminderUpdatableFieldsEquals(ReviewReminder expected, ReviewReminder actual) {
        assertThat(actual)
            .as("Verify ReviewReminder relevant properties")
            .satisfies(a -> assertThat(a.getDueAt()).as("check dueAt").isEqualTo(expected.getDueAt()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getKind()).as("check kind").isEqualTo(expected.getKind()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getDoneAt()).as("check doneAt").isEqualTo(expected.getDoneAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewReminderUpdatableRelationshipsEquals(ReviewReminder expected, ReviewReminder actual) {
        assertThat(actual)
            .as("Verify ReviewReminder relationships")
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()));
    }
}
