package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserStatsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserStatsAllPropertiesEquals(UserStats expected, UserStats actual) {
        assertUserStatsAutoGeneratedPropertiesEquals(expected, actual);
        assertUserStatsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserStatsAllUpdatablePropertiesEquals(UserStats expected, UserStats actual) {
        assertUserStatsUpdatableFieldsEquals(expected, actual);
        assertUserStatsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserStatsAutoGeneratedPropertiesEquals(UserStats expected, UserStats actual) {
        assertThat(actual)
            .as("Verify UserStats auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserStatsUpdatableFieldsEquals(UserStats expected, UserStats actual) {
        assertThat(actual)
            .as("Verify UserStats relevant properties")
            .satisfies(a -> assertThat(a.getCurrentDifficulty()).as("check currentDifficulty").isEqualTo(expected.getCurrentDifficulty()))
            .satisfies(a -> assertThat(a.getTotalAnswered()).as("check totalAnswered").isEqualTo(expected.getTotalAnswered()))
            .satisfies(a -> assertThat(a.getTotalCorrect()).as("check totalCorrect").isEqualTo(expected.getTotalCorrect()))
            .satisfies(a -> assertThat(a.getStreakDays()).as("check streakDays").isEqualTo(expected.getStreakDays()))
            .satisfies(a -> assertThat(a.getLastActiveAt()).as("check lastActiveAt").isEqualTo(expected.getLastActiveAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserStatsUpdatableRelationshipsEquals(UserStats expected, UserStats actual) {
        assertThat(actual)
            .as("Verify UserStats relationships")
            .satisfies(a -> assertThat(a.getSubject()).as("check subject").isEqualTo(expected.getSubject()));
    }
}
